export default interface MovimentacaoDTO {
  id_movimentacao?: number,
  idMovimentacao?: number,
  id_produto?: number,
  idProduto?: number,
  id_movimentacao_origem?: number,
  idMovimentacaoOrigem?: number,
  motivo_movimentacao?: string,
  motivoMovimentacao?: string,
  tipo_movimentacao?: string,
  tipoMovimentacao?: string,
  quantidade?: number,
  preco_unitario?: number,
  precoUnitario?: number,
  valor_total?: number,
  valorTotal?: number,
  observacao?: string,
  data_movimentacao?: Date | string,
  dataMovimentacao?: Date | string,
  ativo?: boolean,
}